### ISSUE TITLE
npm CLI Security Vulnerability - Binary Overwrite in nodeJS <v12.14.0 | update nodeJS to v12.14.0

### ISSUE THREAD

**Issue by JayeshThamke** [cloudfoundry-incubator/service-fabrik-boshrelease#196]
NodeJS - [December 2019 Security Releases](https://nodejs.org/en/blog/vulnerability/december-2019-security-releases/) stated npm CLI is vulnerable to Binary Overwrite of Global node modules. 

As per above Security Release News, it is recommended that the project should be **updated with nodejs v12.14.0 patch**.

`service-fabrik-boshrelease/packages/node/spec` shows _nodeJS v12.13.1_ may have the security loop hole/s.

Could you please verify it? Thanks

regards,
Jayesh Thamke, Steampunk1, DE

**Comment by pivotal-marcela-campo** [comment]
Closing this as version is now `node/node-v12.22.7` ([see here](https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/blob/aa905c6d7457eed20593e7d7ed18bde2d0e654ca/packages/node/spec#L4)
