### ISSUE TITLE
Need IaaS specific provider details for virtual host manager

### ISSUE THREAD

**Issue by pranjaljain** [cloudfoundry-incubator/service-fabrik-boshrelease#30]
Virtual host manager should use a seperate IaaS container to store relationship
between virtual_host instances and deployment name. 
This issue compliments Issue: https://github.com/cloudfoundry-incubator/service-fabrik-broker/issues/122

**Comment by kamath-prasad** [comment]
Currently this has broken -

service fabrik v3.24.0 release .
